homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 71
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  # Customization file
  customize: !include customize.yaml

# Enables the frontend
frontend:

# Enables configuration UI
config:
cloud:

http:
  api_password: !secret api_password
  base_url: !secret base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

google_domains:
  domain: hass.montyavo.com
  username: !secret google_domains_username
  password: !secret google_domains_password

# Checks for available updates
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:
  exclude:
    domains:
      - group
      - sensor.pws_alerts
      - sensor.pws_temp_f
      - sensor.pws_feelslike_f
      - sensor.pws_relative_humidity
      - sensor.pws_wind_mph
      - sensor.pws_precip_today_in
      - sensor.pws_weather
      - sensor.pws_precip_1d_in
      - sensor.pws_precip_1d

map:
sun:
python_script:

### HTML NOTIFICATION ###
notify:
  - name: html5
    platform: html5
    gcm_api_key: !secret html5_server_key
    gcm_sender_id: !secret html5_sender_id

### MQTT BROKER ###
mqtt:
  broker: core-mosquitto
  username: !secret mosq_username
  password: !secret mosq_password

### Z-WAVE CONFIG ###
zwave:
  usb_path: /dev/ttyACM0

### GOOGLE ASSISTANT ###
google_assistant:
  project_id: !secret google-assistant_project_id
  client_id: !secret google-assistant_client_id
  access_token: !secret google-assistant_access_token
  api_key: !secret google-assistant_api_key
  exposed_domains:
    - switch
    - light
    - fan
    - climate
    - input_boolean
    - input_select
  
### Nest Config ###
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
  sensors:
    monitored_conditions:
      - 'humidity'
      - 'hvac_state'
  binary_sensors:
    monitored_conditions:
      - 'online'
      - 'fan'

### iOS ###
ios:
      
### IFTTT Config ###
ifttt:
  key: !secret ifttt_key
  
### Rachio ###
switch:
  - platform: rachio
    access_token: !secret rachio_token
panel_iframe:
  rachio:
    title: Rachio
    url: "https://app.rach.io"
    icon: mdi:water-pump
    
### Device Tracking ###
device_tracker:
  - platform: tplink
    host: !secret tplink_ip
    username: !secret tplink_username
    password: !secret tplink_password
    consider_home: 180
    track_new_devices: false
  - platform: owntracks_http

# Text to speech
tts:
  - platform: google
  
# ffmpeg:
  # ffmpeg_bin: /usr/bin/ffmpeg
# camera:
  # - platform: ffmpeg
    # name: Bedroom Camera
    # input: /dev/video0
### MOTION CAMERA ###
camera:
  - platform: local_file
    name: Bedroom Camera
    file_path: /share/motion/lastsnap.jpg

    
panel_iframe:
  terminal:
    title: Terminal
    icon: mdi:console
    url: http://hassio.local:7681

sensor: !include sensors.yaml
group: !include groups.yaml
automation: !include automations.yaml
automation old: !include_dir_merge_list automations
script: !include scripts.yaml
zone: !include zones.yaml
input_boolean: !include input_booleans.yaml
input_select: !include input_selects.yaml
alert: !include alerts.yaml
