title: Home
resources:
  - url: /local/state-attribute-element.js?v=0
    type: js
  - url: /local/toggle-lock-entity-row.js
    type: js
  - url: /local/entity-attributes-card.js?v=2
    type: js

views:
  - title: default_view
    icon: mdi:home-assistant
    badges:
      # - updater.updater
      - device_tracker.patrick_phone
      - device_tracker.lina_phone
    cards:
      - type: entity-filter
        show_empty: false
        entities:
          - device_tracker.sheree
          - device_tracker.mommy_tirro
        state_filter:
            - home
        card: 
            type: glance
            title: Guests at Home
      
      - type: vertical-stack
        cards:
          - type: sensor
            entity: sensor.house_mode
          - type: entities
            title: Modes
            show_header_toggle: false
            entities:
              # - sensor.house_mode
              - input_select.home_climate_mode
              - input_boolean.show_modes
          - type: conditional
            conditions:
              - entity: input_boolean.show_modes
                state: "on"
            card:
              type: entities
              entities:
                - sensor.house_mode_event
                - type: section
                  label: Away Mode
                - binary_sensor.someone_home
                - entity: input_boolean.away_mode
                  type: custom:toggle-lock-entity-row
                - entity: input_boolean.coming_home
                  type: custom:toggle-lock-entity-row
                - timer.coming_home
                - type: section
                  label: Sleep Mode
                - entity: input_boolean.sleep_mode
                  type: custom:toggle-lock-entity-row
                - entity: input_boolean.waking_up
                  type: custom:toggle-lock-entity-row
                - timer.waking_up

      - type: conditional
        id: christmas_tree
        conditions:
          - entity: input_boolean.christmas_season
            state: "on"
        card:
          type: entity-button
          entity: light.christmas_tree
          tap_action:
            action: toggle
      
      - type: conditional
        id: home_climate_heat
        conditions:
          - entity: input_select.home_climate_mode
            state: 'Heat'
        card:
          type: entities
          title: Climate
          show_header_toggle: false
          entities:
            - type: section
              label: Downstairs
            - entity: climate.downstairs
              name: Living Room
            - climate.dining_room
            - climate.kitchen_main
            - climate.kitchen_rear
            - climate.foyer
            - type: section
              label: Upstairs
            - climate.upstairs
            - climate.master_bath
            - climate.hall_bath
      
      - type: conditional
        id: home_climate_cool
        conditions:
          - entity: input_select.home_climate_mode
            state: 'Cool'
        card:
          type: entities
          title: Climate
          show_header_toggle: false
          entities:
            - type: section
              label: Downstairs
            - entity: climate.downstairs
              name: Downstairs
            - climate.dining_room
            - climate.kitchen_main
            - climate.kitchen_rear
            - climate.foyer
            - type: section
              label: Upstairs
            - climate.upstairs
            - climate.master_bath
            - climate.hall_bath
      
      - type: weather-forecast
        entity: weather.dark_sky
      
      - type: entities
        title: Alarms
        show_header_toggle: false
        entities:
          - type: section
            label: Smoke
          - entity: input_boolean.smoke_alarm
            type: custom:toggle-lock-entity-row
          - sensor.smoke_detector
          - type: section
            label: Leaks
          - entity: input_boolean.leak_alarm
            type: custom:toggle-lock-entity-row
          - entity: switch.main_water_valve_switch
            type: custom:toggle-lock-entity-row
          - group.leak_detectors

### DOWNSTAIRS ###  
  - title: Downstairs
    icon: mdi:arrow-down
    cards:
      - type: entities
        title: Downstairs Lights
        show_header_toggle: true
        entities:
          - light.main_kitchen
          - light.rear_kitchen
          - light.cabinets
          - light.kitchen_chandelier
      - type: entities
        title: Downstairs Climate
        show_header_toggle: false
        entities:
          - climate.downstairs
          - climate.dining_room
          - climate.kitchen_main
          - climate.kitchen_rear
          - climate.foyer
      - type: horizontal-stack
        cards:
          - type: media-control
            entity: media_player.first_floor
          - type: media-control
            entity: media_player.living_room_speaker
          - type: media-control
            entity: media_player.kitchen_speaker
          - type: media-control
            entity: media_player.living_room_tv
      - type: entities
        entities:
          - media_player.first_floor
          - media_player.living_room_speaker
          - media_player.kitchen_speaker
          - media_player.living_room_tv

### UPSTAIRS ###  
  - title: Upstairs
    icon: mdi:arrow-up
    cards:
      - type: entities
        title: Master Bedroom
        show_header_toggle: true
        entities:
          - entity: switch.bedroom_light_switch
            name: Overhead Light
          - light.bedside
          - fan.bedroom_fan_level
          - light.master_bathroom_light_level
          - entity: switch.humidifier_switch
            name: Humidifier
      - type: entities
        title: 3rd Floor
        show_header_toggle: true
        entities:
          - sensor.multisensor_temperature
          - sensor.multisensor_relative_humidity
      - type: entities
        title: Upstairs Climate
        show_header_toggle: false
        entities:
          - climate.upstairs
          - climate.master_bath
          - climate.hall_bath
          - sensor.upstairs_thermostat_humidity
          - group.upstairs_climate_status
      - type: picture-entity
        title: Bedroom Camera
        entity: camera.bedroom_camera
        camera_image: camera.bedroom_camera
        show_info: true
      - type: picture-entity
        title: Nursery Camera
        entity: camera.nursery_camera
        camera_image: camera.nursery_camera
        show_info: true
      - type: entities
        title: Laundry Room
        show_header_toggle: true
        entities:
          - binary_sensor.laundry_leak_sensor
      - type: horizontal-stack
        cards:
          - type: media-control
            entity: media_player.upstairs
          - type: media-control
            entity: media_player.master_speaker
          - type: media-control
            entity: media_player.nursery_speaker
          - type: media-control
            entity: media_player.3rd_floor_speaker
          - type: media-control
            entity: media_player.bedroom_tv

### OUTSIDE ###  
  - title: Outside
    icon: mdi:tree
    badges:
      - sun.sun
      - sensor.outside_temperature
      - sensor.outside_humidity
    cards:
      - type: entities
        title: Outside Lights
        show_header_toggle: true
        entities:
          - switch.front_lights
          - switch.deck_light_switch
          - switch.driveway_switch
      - type: vertical-stack
        cards:
        - type: entities
          title: Irrigation
          show_header_toggle: false
          entities:
            - binary_sensor.rachio_online
        - type: iframe
          url: !secret rachio_zones_url
          aspect_ratio: 125%

### CAMERAS VIEW ###
  - title: Cameras
    icon: mdi:camcorder
    cards:
      - type: picture-entity
        title: Bedroom Camera
        entity: camera.bedroom_camera
        camera_image: camera.bedroom_camera
        show_info: true
      - type: picture-entity
        title: Nursery Camera
        entity: camera.nursery_camera
        camera_image: camera.nursery_camera
        show_info: true

# ### 1ST FLOORPLAN ###
#   - icon: mdi:numeric-1-box
#     title: 1st Floorplan
#     id: floorplan1
#     panel: true
#     cards:
#       - type: picture-elements
#         image: /local/FirstFloorPlan.png
#         elements:
#           - type: custom:state-attribute-element
#             entity: climate.downstairs
#             attribute: current_temperature
#             style:
#               top: 80%
#               left: 47%
#           - type: state-label
#             entity: sensor.upstairs_climate_status
#             style:
#               top: 82%
#               left: 79%
#           - type: service-button
#             title: Turn lights off
#             style:
#               top: 95%
#               left: 80%
#             service: light.turn_off
#             service_data:
#                 entity_id: group.downstairs_lights

# ### 2ND FLOORPLAN ###                
#   - icon: mdi:numeric-2-box
#     title: 2nd Floorplan
#     id: floorplan2
#     panel: true
#     cards:
#       - type: picture-elements
#         image: /local/SecondFloorPlan.png
#         elements:
#           - type: custom:state-attribute-element
#             entity: climate.upstairs
#             attribute: temperature
#             suffix: °
#             style:
#               top: 51%
#               left: 60%
#           - type: state-icon
#             entity: climate.upstairs
#             style:
#               top: 55%
#               left: 60%
#           - type: state-icon
#             tap_action: 
#               action: toggle
#             entity: switch.bedroom_light_switch
#             style:
#               top: 35%
#               left: 34%
#           - type: state-icon
#             tap_action: 
#               action: toggle
#             entity: fan.bedroom_fan_level
#             style:
#               top: 30%
#               left: 34%
#           - type: state-icon
#             tap_action: 
#               action: toggle
#             entity: light.master_bathroom_light_level
#             style:
#               top: 28%
#               left: 54%
#           - type: state-icon
#             entity: climate.master_bath
#             style:
#               top: 30%
#               left: 59%
#           # - type: custom:state-attribute-element
#           #   entity: climate.master_bath
#           #   attribute: temperature
#           #   suffix: °
#           #   style:
#           #     top: 26%
#           #     left: 59%
#           # - type: state-icon
#           #   entity: climate.hall_bath
#           #   style:
#           #     top: 15%
#           #     left: 71%
#           # - type: custom:state-attribute-element
#           #   entity: climate.hall_bath
#           #   attribute: temperature
#           #   suffix: °
#           #   style:
#           #     top: 11%
#           #     left: 71%
#           - type: state-icon
#             tap_action: 
#               action: toggle
#             entity: light.bedside
#             style:
#               top: 22%
#               left: 24%
#           - type: state-icon
#             entity: media_player.bedroom_tv
#             style:
#               top: 21%
#               left: 42%
#           - type: icon
#             entity: camera.bedroom_camera
#             icon: mdi:cctv
#             style:
#               top: 25%
#               left: 42%
#           - type: icon
#             entity: camera.nursery_camera
#             icon: mdi:cctv
#             style:
#               top: 65%
#               left: 75%
#           - type: state-icon
#             entity: binary_sensor.laundry_leak_sensor
#             style:
#               top: 24%
#               left: 74%

### SETTINGS ###
  - title: Settings
    icon: mdi:tune
    cards:
      - type: entities
        title: Settings
        show_header_toggle: false
        entities:
          - type: call-service
            name: Set Thermostats
            service: python_script.set_thermostats
            icon: mdi:thermostat-box
            action_name: Set
          - entity: input_boolean.christmas_season
            type: custom:toggle-lock-entity-row
      - type: entities
        title: Automations and Scripts
        show_header_toggle: true
        entities:
          - group.all_automations
          - group.all_scripts
      - type: shopping-list
        title: To Do List
      - type: entities
        title: Speedtest
        show_header_toggle: true
        entities:
          - sensor.speedtest_ping
          - sensor.speedtest_download
          - sensor.speedtest_upload

### TEST ###
  - title: Test
    icon: mdi:test-tube
    cards:
      - type: entities
        title: Christmas Tree & Vegetable Lights
        entities:
          - switch.christmas_vegetable
          - input_boolean.christmas_season
          - light.christmas_tree
      - type: entities
        entities:
          - sensor.living_room_heating
          - sensor.nursery_camera_motion_detected
      - type: entities
        title: Google Calendar
        show_header_toggle: false
        entities:
          - calendar.home_assistant
          - type: custom:entity-attributes-card
            title: Attributes Card
            heading_name: List
            heading_state: States
            filter:
              include:
                - key: calendar.home_assistant.*
      - type: history-graph
        title: Outside Temp & Living Room Heating
        hours_to_show: 168
        entities:
          - sensor.outside_temperature
          - sensor.living_room_heating
      - type: sensor
        entity: sensor.outside_temperature
        graph: line
      - type: history-graph
        title: Dark Sky Precip Sensors
        hours_to_show: 24
        entities:
          - sensor.dark_sky_precip_probability_0
          - sensor.dark_sky_precip_intensity_0
