#################################################################
## Lovelace
#################################################################
# This is a bootstrap for my Lovelace configuration based on frenck.
#
# Views are included one by one, this to guarentee the order of
# the tabs of the view in the UI.
#
title: Home
resources:
  - url: /local/state-attribute-element.js?v=0
    type: js
  - url: /local/toggle-lock-entity-row.js
    type: js
  - url: /local/entity-attributes-card.js?v=2
    type: js
views:
  - !include lovelace/views/home.yaml
  - !include lovelace/views/downstairs.yaml
  - !include lovelace/views/upstairs.yaml
  - !include lovelace/views/outside.yaml
  - !include lovelace/views/cameras.yaml
  - !include lovelace/views/settings.yaml
  - !include lovelace/views/testing.yaml