#################################################################
## Binary Sensors
#################################################################

binary_sensor:
  - platform: rachio
  
  - platform: template
    sensors:
      someone_home:
        friendly_name: "Someone Home"
        device_class: presence
        value_template: "{{ is_state('group.all_devices', 'home') }}"
        