#################################################################
## HVAC Automation
#################################################################

  - alias: Home Mode Change, Set Thermostats
    trigger:
      - platform: state
        entity_id: sensor.house_mode
    action:
      - delay: 0:00:05
      - service: python_script.set_thermostats

  - alias: Humidifier OFF for bed
    initial_state: True
    hide_entity: False
    trigger:
      platform: time
      at: '04:00:00'
    action:
      service: switch.turn_off
      entity_id: switch.humidifier_switch
  
  ### Automations for the Whole Home HVAC Mode Selecter ###
  - alias: Any HVAC mode Change, change Whole home selecter
    trigger:
      - platform: state
        entity_id: sensor.downstairs_op_mode
    condition:
      condition: template
      value_template: " {{ states('sensor.downstairs_op_mode') != 'eco' }} "
    action:
      - service: input_select.select_option
        data_template: 
          entity_id: input_select.home_climate_mode
          option: "{{ states('sensor.downstairs_op_mode')|title }}"

  - alias: Change whole home selecter, change all HVAC modes
    trigger:
      - platform: state
        entity_id: input_select.home_climate_mode
    action:
      - service: climate.set_operation_mode
        data_template:
          entity_id: group.downstairs_climate, climate.upstairs, climate.master_bath, climate.hall_bath
          operation_mode: "{{ states('input_select.home_climate_mode')|lower }}"
      - delay: 0:00:05
          
  - alias: Humidifier ON for bed
    initial_state: True
    hide_entity: False
    trigger:
      - platform: time
        at: '21:00:00'
      - platform: state
        entity_id: sensor.house_mode
        to: 'Home'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: sensor.house_mode
          state: 'Home'
        - condition: time
          after: '21:00:00'
        - condition: template
          value_template: "{{ is_state_attr('climate.upstairs', 'operation_mode', 'heat') }}"
    action:
      service: switch.turn_on
      entity_id: switch.humidifier_switch