#################################################################
## Other Automations
#################################################################

  - alias: Home Assistant Start Notification
    trigger:
      - platform: homeassistant
        event: start
    action:
      - service: persistent_notification.create
        data:
          title: "Home Assistant"
          message: "Successfully started!"

  - alias: Smoke Alarm ON
    trigger:
      - platform: state
        entity_id: input_boolean.smoke_alarm
        to: 'on'
    action:
      - service: mqtt.publish
        data:
          topic: home/safety/smoke_detector
          payload_template: 'Last Alarm: {{ now().month }}/{{ now().day }}/{{ now().year}} @ {{ now().hour }}:{{ now().minute }}:{{ now().second }}'
          retain: True
      - service: switch.turn_on
        data:
          entity_id: switch.front_main
      - delay: 0:10
      - service: switch.turn_on
        data:
          entity_id: switch.back_walkway
          
  - alias: Bedroom Light Toggle Webhook
    trigger:
      platform: webhook
      webhook_id: !secret webhook_bedroom_light_toggle
    action:
      service: switch.toggle
      entity_id: switch.bedroom_light_switch
      
  - alias: Smoke Alarm ON when Receive Roost Webhook from IFTTT
    trigger:
      platform: webhook
      webhook_id: !secret webhook_smoke_alarm
    action:
      service: input_boolean.turn_on
      entity_id: input_boolean.smoke_alarm    
  
  - alias: Inside Lights off when Away
    trigger:
      platform: state
      entity_id: sensor.house_mode
      to: 'Away'
    action:
      service: homeassistant.turn_off
      entity_id: group.inside_lights

  - alias: Certain Inside Lights On when Awake/Arrive at Dark
    trigger:
      - platform: state
        entity_id: sensor.house_mode_event
        to: 'Arrived Home'
      - platform: state
        entity_id: sensor.house_mode_event
        to: 'Woke Up'
    condition:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
    action:
      service: homeassistant.turn_on
      entity_id: group.inside_entry_lights

  - alias: Christmas Tree ON while Home during Christmas Season
    trigger:
      - platform: state
        entity_id: sensor.house_mode
    condition:
      - condition: state
        entity_id: input_boolean.christmas_season
        state: "on"
    action:
      service_template: >
        {% if states('sensor.house_mode') == 'Home' %}
          light.turn_on
        {% else %}
          light.turn_off
        {% endif %}
      data:
        entity_id: light.christmas_tree
  
  - alias: Vegetable Light ON at 5am
    trigger:
      - platform: time
        at: '05:00:00'
    action:
      service: switch.turn_on
      entity_id: switch.vegetable_light_switch
      
  - alias: Vegetable Light OFF at 8:30pm
    trigger:
      - platform: time
        at: '20:30:00'
    action:
      service: switch.turn_off
      entity_id: switch.vegetable_light_switch